version: '3'

networks:
  my_network:
    driver: bridge

services:
  backend1:
    build:
      context: ./backend1
    environment:
      - NAME=Backend1
      - PORT=5001
    ports:
      - "5001:5001"
    networks:
      - my_network

  backend2:
    build:
      context: ./backend2
    environment:
      - NAME=Backend2
      - PORT=5002
    ports:
      - "5002:5002"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
