version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2

  backend1:
    build: ./backend/backend1
    container_name: backend1
    ports:
      - "3001:80"

  backend2:
    build: ./backend/backend2
    container_name: backend2
    ports:
      - "3002:80"
