version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-data:
