version: '4.2'
services:
    database:
      image: mysql
      ports:
      - "3306:3306"
      environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demo
    web:
     image: dcomposeapp   
     ports:
      - "80"
                                                                                                            